### ISSUE TITLE
Furnace makes infected Charcoal 1.1.26

### ISSUE THREAD

**Issue by BonaireDreams** [NFINIT-Development/AstroBlock#44]
Astroblock 1.1.26
Redstone furnace was cooking Oak into charcoal, after going to overworld and coming back to station. Same furnace now only produced Infected Charcoal. Breaking and replacing furnace does not resolve.
Normal furnace still produces normal charcoal.

**Comment by knoxhack** [comment]
Fixed in 1.1.27

**Comment by BonaireDreams** [comment]
Still getting infected charcoal from TE Redstone furnace in 1.1.27. Basic furnace with no upgrades.

**Comment by reportingbug** [comment]
Redstone furnace makes infected charcoal from normal oak logs in v 1.1.31
